Repository halo-dev/theme-earth, pull requests merged in 2022-12, with the labels that each got.

#21 refactor: use literal substitutions to improve th:class and th:text
  templates/category.html
  templates/index.html
  templates/modules/featured-post-card.html
  templates/modules/post-card.html
  templates/modules/tag-filter.html
  templates/modules/widgets/tags.html
  templates/page.html
  templates/post.html
  templates/tag.html
  templates/tags.html
Labels: release-note-none, lgtm, approved, kind/improvement

#22 feat: add exception pages
  templates/assets/dist/style.css
  templates/error/error.html
Labels: kind/feature, release-note-none, lgtm, approved

#24 fix: Logo is not displayed properly
  templates/modules/footer.html
Labels: kind/bug, release-note, lgtm, approved

#23 feat: add author archive template
  templates/assets/dist/style.css
  templates/author.html
  templates/modules/featured-post-card.html
  templates/modules/post-card.html
  templates/page.html
  templates/post.html
Labels: kind/feature, release-note, lgtm, approved

#30 chore: add LICENSE
  LICENSE
Labels: release-note-none, lgtm, approved, kind/improvement

#29 refactor: mobile menu style
  templates/assets/dist/style.css
  templates/modules/header.html
  templates/modules/layout.html
  templates/modules/overlay-menu.html
Labels: release-note-none, lgtm, approved, kind/improvement

#31 refactor: separate hero image from header component
  src/styles/main.css
  templates/assets/dist/style.css
  templates/author.html
  templates/category.html
  templates/index.html
  templates/links.html
  templates/modules/header.html
  templates/modules/hero.html
  templates/modules/layout.html
  templates/page.html
  templates/post.html
  templates/tag.html
  templates/tags.html
Labels: release-note-none, lgtm, approved, kind/improvement

#32 refactor: color scheme switcher
  src/alpine-data/color-scheme-switcher.ts
  src/main.ts
  tailwind.config.cjs
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/modules/header.html
Labels: release-note-none, lgtm, approved, kind/improvement

#33 chore: release 1.1.0
  package.json
  theme.yaml
Labels: release-note-none, lgtm, approved, kind/improvement

#34 fix: error template render
  templates/error/error.html
Labels: kind/bug, release-note-none, lgtm, approved

#36 fix: links of links page are not bound url
  templates/links.html
Labels: kind/bug, release-note-none, lgtm, approved

#37 chore: release 1.1.1
  package.json
  theme.yaml
Labels: release-note-none, lgtm, approved, kind/improvement
