Repository halo-dev/theme-earth, pull requests merged in 2023-06, with the labels that each got.

#81 refactor: change the url of the post editing route
  templates/modules/header.html
  templates/page.html
  templates/post.html
Labels: release-note, lgtm, approved, kind/improvement

#82 chore: release 1.4.0
  templates/assets/dist/style.css
  theme.yaml
Labels: release-note-none, lgtm

#85 fix: fix the post sidebar_prepend zindex
  templates/post.html
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#88 chore: bump dependencies
  package.json
  pnpm-lock.yaml
  tailwind.config.cjs
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
Labels: release-note-none, lgtm, approved, kind/improvement
