Repository halo-dev/theme-earth, pull requests merged in 2023-02, with the labels that each got.

#47 feat: add supports for disabled comment
  templates/page.html
  templates/post.html
Labels: kind/feature, release-note-none, lgtm, approved

#48 feat: add upvote supports to post
  src/alpine-data/post-upvote.ts
  src/main.ts
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/post.html
Labels: kind/feature, release-note, lgtm, approved

#52 fix: logo width issue in some old browser
  templates/modules/header.html
Labels: kind/bug, release-note, lgtm, approved
