Repository halo-dev/theme-earth, pull requests merged in 2023-07, with the labels that each got.

#90 pref: optimize toc to remove empty directories and fix some bugs
  src/main.ts
  src/styles/main.css
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/modules/sidebar.html
  templates/post.html
Labels: release-note, lgtm, approved, kind/improvement

#89 feat: add filters to the cover image
  src/styles/main.css
  templates/assets/dist/style.css
  templates/modules/footer.html
  templates/modules/hero.html
  templates/modules/layout.html
  templates/post.html
Labels: kind/feature, release-note, lgtm, approved

#97 feat: add setting items for Chinese public security filing information
  settings.yaml
  templates/assets/images/gongan_beian.png
  templates/modules/footer.html
Labels: release-note, lgtm, approved

#98 refactor: refine footer layout
  templates/assets/dist/style.css
  templates/modules/footer.html
Labels: release-note-none, lgtm, approved, kind/improvement

#96 feat: add image support for social media
  templates/assets/dist/style.css
  templates/modules/footer-social.html
  templates/modules/footer.html
Labels: kind/feature, release-note, lgtm, approved

#99 chore: release 1.5.0
  templates/assets/dist/style.css
  theme.yaml
Labels: release-note-none, lgtm, approved
