Repository halo-dev/theme-earth, pull requests merged in 2023-04, with the labels that each got.

#64 perf: remove pointer cursor style for post card container
  templates/modules/post-card.html
Labels: release-note, lgtm, approved

#72 fix the problem that the footer title does not display
  templates/modules/footer.html
Labels: release-note-none, lgtm, approved, kind/improvement

#73 feat: add post archives template
  templates/archives.html
  templates/assets/dist/style.css
Labels: kind/feature, release-note, lgtm, approved

#74 feat: add sticky supports for post toc
  templates/post.html
Labels: kind/feature, release-note, lgtm, approved
