Repository halo-dev/theme-earth, pull requests merged in 2023-03, with the labels that each got.

#58 chore: release 1.2.0
  package.json
  theme.yaml
Labels: release-note-none, lgtm, approved, kind/improvement

#56 feat: adapt the target attribute of the menuitem
  templates/modules/header.html
  theme.yaml
Labels: kind/feature, release-note, lgtm, approved

#57 chore: bump dependencies
  package.json
  pnpm-lock.yaml
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
Labels: release-note-none, lgtm, approved, kind/improvement

#60 fix: single page not working
  templates/page.html
Labels: kind/bug, release-note, lgtm, approved

#61 chore: release 1.2.1
  package.json
  theme.yaml
Labels: release-note-none, lgtm, approved

#62 add rss icon in sidebar media selection
  settings.yaml
  tailwind.config.cjs
  templates/assets/dist/style.css
Labels: release-note-none, lgtm, approved
