Repository halo-dev/theme-earth, pull requests merged in 2024-04, with the labels that each got.

#131 feat: improve accessibility of profile widget
  templates/modules/widgets/profile.html
Labels: release-note-none, lgtm, approved

#137 chore: cleanup inject code of comment widget
  templates/moments.html
  templates/page.html
  templates/post.html
Labels: kind/cleanup, release-note-none, lgtm, approved

#138 chore: bump dependencies
  package.json
  pnpm-lock.yaml
  src/main.ts
  templates/archives.html
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/links.html
  templates/modules/category-tree.html
  templates/modules/featured-post-card.html
  templates/modules/footer-social.html
  templates/modules/footer.html
  templates/modules/header.html
  templates/modules/post-card.html
  templates/modules/share-modal.html
  templates/modules/widgets/latest-comments.html
  templates/modules/widgets/popular-posts.html
  templates/modules/widgets/profile.html
  templates/moments.html
  templates/page.html
  templates/post.html
Labels: release-note-none, lgtm, approved, kind/improvement

#139 feat: add support for image formats to social media settings
  templates/modules/footer-social.html
  templates/modules/image-view-modal.html
  templates/modules/widgets/profile.html
Labels: kind/feature, release-note, lgtm, approved

#140 fix: background color issue
  src/styles/main.scss
  templates/assets/dist/style.css
Labels: kind/bug, release-note-none, lgtm, approved

#144 chore: update theme.yaml
  theme.yaml
Labels: release-note-none, lgtm, approved

#146 feat: add issues field for theme manifest
  theme.yaml
Labels: release-note, lgtm, approved, kind/improvement
