Repository halo-dev/theme-earth, pull requests merged in 2024-11, with the labels that each got.

#207 feat: add preload tag for logo image
  templates/modules/layout.html
Labels: kind/feature, release-note

#206 fix: add target attribute to footer menu links
  templates/modules/footer.html
Labels: kind/bug, release-note, approved

#210 refactor: improve posts pagination with direct page navigation
  src/styles/main.scss
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/category.html
  templates/index.html
  templates/modules/pagination.html
  templates/moments.html
  templates/photos.html
  templates/tag.html
Labels: release-note

#213 feat: add setting option for post title position
  .gitignore
  settings.yaml
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/page.html
  templates/post.html
Labels: release-note

#212 fix: missing post count display in category listing
  templates/modules/category-tree.html
  templates/modules/tag-filter.html
  templates/modules/widgets/tags.html
Labels: kind/bug, release-note

#211 chore: bump dependencies
  package.json
  pnpm-lock.yaml
  tailwind.config.cjs
  vite.config.ts
Labels: release-note-none

#209 fix: resolve CLS issues in page layout
  templates/archives.html
  templates/links.html
  templates/modules/layout.html
  templates/modules/sidebar.html
  templates/moments.html
  templates/photos.html
Labels: release-note, kind/improvement

#214 feat: add i18n supports
  env.d.ts
  i18n/en.properties
  i18n/es.properties
  i18n/zh_CN.properties
  i18n/zh_TW.properties
  src/alpine-data/color-scheme-switcher.ts
  src/alpine-data/share.ts
  src/alpine-data/upvote.ts
  templates/archives.html
  templates/author.html
  templates/category.html
  templates/error/error.html
  templates/index.html
  templates/links.html
  templates/modules/category-filter.html
  templates/modules/featured-post-card.html
  templates/modules/header.html
  templates/modules/layout.html
  templates/modules/pagination.html
  templates/modules/post-card.html
  templates/modules/share-modal.html
  templates/modules/tag-filter.html
  templates/modules/widgets/categories.html
  templates/modules/widgets/latest-comments.html
  templates/modules/widgets/popular-posts.html
  templates/modules/widgets/profile.html
  templates/modules/widgets/tags.html
  templates/moments.html
  templates/page.html
  templates/photos.html
  templates/post.html
  templates/tag.html
  templates/tags.html
Labels: kind/feature, release-note, lgtm, approved

#215 feat: add logo type setting option
  settings.yaml
  templates/modules/header.html
Labels: release-note

#216 feat: add categories template
  i18n/en.properties
  i18n/es.properties
  i18n/zh_CN.properties
  i18n/zh_TW.properties
  templates/categories.html
  templates/modules/category-filter.html
Labels: kind/feature, release-note, lgtm, approved

#217 fix: improve category filter accessibility on mobile devices
  templates/modules/category-filter.html
Labels: release-note, lgtm

#218 refactor: improve color scheme switcher
  i18n/zh_CN.properties
  src/alpine-data/color-scheme-switcher.ts
  templates/modules/header.html
Labels: release-note, kind/improvement

#220 fix: correct Chinese translation for pagination 'next page' text
  i18n/zh_CN.properties
Labels: kind/bug, release-note

#222 fix: add styling to pagination dropdown options
  templates/modules/pagination.html
Labels: release-note, lgtm, approved

#221 fix: update subtitle opacity for better visibility in hero module
  templates/modules/hero.html
Labels: release-note, lgtm, approved
