Repository halo-dev/theme-earth, pull requests merged in 2024-09, with the labels that each got.

#177 refactor: optimize post edit button position
  templates/assets/dist/style.css
  templates/modules/layout.html
  templates/page.html
  templates/post.html
Labels: release-note, lgtm, approved

#176 refactor: add condition for icp config
  templates/modules/footer.html
Labels: release-note-none, lgtm, approved

#179 feat: improve accessibility of scroll-to-top button
  templates/modules/layout.html
Labels: release-note-none, lgtm, approved

#172 feat: add supports for responsive image
  templates/modules/featured-post-card.html
  templates/modules/post-card.html
  templates/moments.html
  templates/photos.html
  theme.yaml
Labels: kind/support, release-note, lgtm, approved

#183 feat: add comment widget supports for links page
  templates/links.html
Labels: release-note, lgtm, approved

#184 refactor: simplify the setting form
  settings.yaml
  src/alpine-data/share.ts
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/links.html
  templates/modules/footer-social.html
  templates/modules/footer.html
  templates/post.html
Labels: release-note, lgtm, approved
