Repository halo-dev/theme-earth, pull requests merged in 2024-08, with the labels that each got.

#148 chore: fix unavailable prettier task config
  package.json
  templates/modules/footer.html
  templates/modules/post-card.html
  templates/modules/share-modal.html
  templates/moments.html
  templates/page.html
  templates/post.html
Labels: release-note-none, lgtm, approved

#162 chore: integrate husky and lint-staged for pre-commit code formatting
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: release-note-none, lgtm, approved

#159 refactor: logout
  src/alpine-data/logout.ts
  src/main.ts
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/modules/header.html
Labels: release-note, lgtm, approved

#161 feat: add scroll to top button
  settings.yaml
  src/main.ts
  templates/assets/dist/main.iife.js
  templates/assets/dist/style.css
  templates/modules/footer.html
  templates/modules/header.html
  templates/modules/hero.html
  templates/modules/layout.html
  templates/modules/post-card.html
  templates/modules/share-modal.html
  templates/modules/tag-filter.html
  templates/modules/widgets/tags.html
  templates/moments.html
  templates/page.html
  templates/post.html
Labels: kind/feature, release-note, approved

#164 fix: resolve link display issue in share modal
  templates/modules/share-modal.html
Labels: kind/bug, release-note, lgtm, approved

#163 feat: add color customization for hero section title on homepage
  settings.yaml
  templates/modules/hero.html
Labels: kind/feature, release-note, lgtm, approved

#165 feat: add support for hiding upvote and share buttons on posts
  settings.yaml
  templates/post.html
Labels: kind/feature, release-note, lgtm, approved

#167 fix: resolve issue with default title text color not being applied
  settings.yaml
Labels: release-note, lgtm, approved

#169 fix: resolve issue with footer menu items not displaying
  templates/modules/footer.html
Labels: kind/bug, release-note, lgtm, approved
