Repository halo-dev/theme-earth, pull requests merged in 2024-10, with the labels that each got.

#188 refactor: change login url
  src/alpine-data/logout.ts
  src/main.ts
  templates/modules/header.html
  theme.yaml
Labels: release-note, lgtm, approved, kind/improvement

#189 refactor: redirect to current url after login
  templates/modules/header.html
Labels: do-not-merge/release-note-label-needed

#191 feat: refine dark mode for menu divider
  templates/modules/header.html
Labels: release-note-none, lgtm, approved

#196 Fix the problem of not displaying while configuring ICP only
  templates/modules/footer.html
Labels: release-note, lgtm, approved

#200 feat: support dynamic html language attribute
  templates/modules/layout.html
Labels: kind/feature, release-note, lgtm, approved
